startDelaySeconds: 0
#hostPort: 127.0.0.1:1234
username:
password:
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:12345/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false

# Include Jetty and JVM metrics object names
includeObjectNames:
  # Jetty server metrics
  - "org.eclipse.jetty.server:type=*"
  - "org.eclipse.jetty.util:type=*"
  - "org.eclipse.jetty.io:type=*"

  # JVM metrics
  - "java.lang:type=Memory"
  - "java.lang:type=Threading"
  - "java.lang:type=OperatingSystem"
  - "java.lang:type=GarbageCollector,*"
  - "java.lang:type=Compilation"
  - "java.lang:type=ClassLoader"
  - "java.lang:type=Runtime"

excludeObjectNames: []
autoExcludeObjectNameAttributes: true
excludeObjectNameAttributes:
  "java.lang:type=OperatingSystem":
    - "ObjectName"
  "java.lang:type=Runtime":
    - "ClassPath"
    - "SystemProperties"

rules:
  # Jetty server metrics
  - pattern: 'org.eclipse.jetty.server<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jetty_server_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "Jetty Server metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  - pattern: 'org.eclipse.jetty.util<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jetty_util_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "Jetty Util metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  - pattern: 'org.eclipse.jetty.io<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jetty_io_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "Jetty IO metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM Memory metrics
  - pattern: 'java.lang:type=Memory<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_memory_$1_$2
    value: $3
    labels: {}
    help: "JVM Memory metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM Threading metrics
  - pattern: 'java.lang:type=Threading<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_threads_$1_$2
    value: $3
    labels: {}
    help: "JVM Threading metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM Garbage Collection metrics
  - pattern: 'java.lang:type=GarbageCollector,name=(\w+)<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_gc_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "JVM Garbage Collection metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM Compilation metrics
  - pattern: 'java.lang:type=Compilation<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_compilation_$1_$2
    value: $3
    labels: {}
    help: "JVM Compilation metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM ClassLoader metrics
  - pattern: 'java.lang:type=ClassLoader<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_classloader_$1_$2
    value: $3
    labels: {}
    help: "JVM ClassLoader metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false

  # JVM Runtime metrics
  - pattern: 'java.lang:type=Runtime<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: jvm_runtime_$1_$2
    value: $3
    labels: {}
    help: "JVM Runtime metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false
