#!/bin/bash

#set -x
set -eo pipefail

APP_HOME=/opt/hub
APP_JAR=$(ls ${APP_HOME}/lib/hub-*)
CLASSPATH=${APP_JAR}:${APP_HOME}/lib/*
CONFIG_DIR=/etc/hub
# LOG_DIR also exists in logback.xml
LOG_DIR=/mnt/log
DEBUG_PORT=3333
HOST_IP=${HUB_RMI_HOST_IP:=disabled.host.for.rmi}
JMXREMOTE_PORT=8888

# extract the port from hub.properties
for word in $(<${CONFIG_DIR}/hub.properties); do
    if [[ ${word} == http.bind_port* ]]; then
        APP_PORT=$(echo ${word} | cut -d '=' -f 2)
    fi
done

# Account for encrypted hub flavor
if [[ $APP_PORT == "8443"  || $APP_PORT == "443" ]]; then
  CURL="curl -kis -X POST https://"
else
  CURL="curl -is -X POST http://"
fi

JAVA_OPTS="
 -d64
 -server
 -Xmx$MAX_HEAP
 -Xms$MIN_HEAP
 -XX:NewSize=$NEW_SIZE
 -XX:+UseG1GC
 -XX:MaxGCPauseMillis=100
 -XX:+ExitOnOutOfMemoryError
 -Dsun.rmi.dgc.client.gcInterval=300000
 -Dsun.rmi.dgc.server.gcInterval=300000
 -agentlib:jdwp=transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=n
 -Djboss.platform.mbeanserver
 -Dcom.sun.management.jmxremote
 -Dcom.sun.management.jmxremote.local.only=false
 -Djava.rmi.server.hostname=$HOST_IP
 -Dcom.sun.management.jmxremote.port=$JMXREMOTE_PORT
 -Dcom.sun.management.jmxremote.rmi.port=$JMXREMOTE_PORT
 -Dcom.sun.management.jmxremote.ssl=false
 -Dcom.sun.management.jmxremote.authenticate=false
 -XX:+PrintGCDetails
 -XX:+PrintTenuringDistribution
 -XX:+PrintGCDateStamps
 -Djava.awt.headless=true
 -Dsun.net.inetaddr.ttl=0
 -Xloggc:${LOG_DIR}/gc.log-$(date -u '+%Y-%m-%d-%H-%M-%S')
 -Dfile.encoding=UTF-8
 -Dlogback.configurationFile=${CONFIG_DIR}/logback.xml"

CHILDPID=""
function shutdownChild()
{
    echo "signal trap caught - taking stack trace and sleeping 5s before relaying signal"

    if [ -z "$CHILDPID" ]
    then
        echo "no hub child PID to shutdown"
        return
    fi

    kill -QUIT ${CHILDPID}

    echo "issuing shutdown curl command..."
    ${CURL}localhost:${APP_PORT}/shutdown

    kill -TERM ${CHILDPID}
    echo "signal sent, waiting ..."
    wait ${CHILDPID}
    echo "hub is down"
}
trap "shutdownChild" SIGTERM SIGINT

echo "running hub in the background..."
exec java -cp ${CLASSPATH} ${JAVA_OPTS} com.flightstats.hub.app.HubMain ${CONFIG_DIR}/hub.properties &
CHILDPID=$!
echo "... hub pid is $CHILDPID"

wait ${CHILDPID}
exit $?